name: Android CI
on: workflow_dispatch

jobs:
  android-ndll:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib dev lime $GITHUB_WORKSPACE

      - name: Enable HXCPP compile cache
        run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      - name: Configure Android support
        run: |
          haxelib run lime setup -alias -y
          lime config ANDROID_SDK $ANDROID_HOME
          lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          lime config JAVA_HOME $JAVA_HOME_11_X64
          lime config ANDROID_SETUP true

      - name: Rebuild Lime (Android)
        run: |
          lime rebuild android -D HXCPP_ARM64 -final -eval -nocolor -verbose -nocffi

      - uses: actions/upload-artifact@v3
        with:
          name: Android-NDLL
          path: |
            ndll/Android/
            !**/.gitignore
          if-no-files-found: error
