name: Android CI
on: workflow_dispatch

jobs:
  android-ndll:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          sudo apt-get install -qq libgl1-mesa-dev libglu1-mesa-dev libpulse-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib dev lime $GITHUB_WORKSPACE

      - name: Enable HXCPP compile cache
        run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      - name: Configure Android support
        run: |
          haxelib run lime setup -alias -y
          lime config ANDROID_SDK $ANDROID_HOME
          lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          lime config JAVA_HOME $JAVA_HOME_11_X64
          lime config ANDROID_SETUP true

      - name: Rebuild Lime (Android AArch32)
        run: lime rebuild android -D HXCPP_ARMV7 -release -eval -nocolor -nocffi
        continue-on-error: true

      - name: Rebuild Lime (Android AArch64)
        run: lime rebuild android -D HXCPP_ARM64 -release -eval -nocolor -nocffi
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: Android-NDLL
          path: |
            ndll/Android/
            !**/.gitignore
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: Linux64-NDLL
          path: |
            ndll/Linux64/
            !**/.gitignore
          if-no-files-found: error
